version: "3.7"

services:
  api:
    container_name: dev_echo_blog_api
    build:
      context: ./api/
      dockerfile: Dockerfile.dev
    ports:
      - 1323:1323
    links:
      - db
    volumes:
      - ./api:/go/src/github.com/yongwoon/echo-blog
    networks:
      - dev_echo_blog_network
  db:
    container_name: dev_echo_blog_db
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: >
      mysqld
        --default-authentication-plugin=mysql_native_password
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_general_ci
    ports:
      - "3307:3306"
    security_opt:
      - seccomp:unconfined
    volumes:
      - dev_go_blog_db_volume:/var/lib/mysql
    networks:
      - dev_echo_blog_network
volumes:
  dev_go_blog_db_volume:
networks:
  dev_echo_blog_network:
