FROM golang:1.14.4-alpine

LABEL maintainer="https://github.com/yongwoon"

ENV GO111MODULE=on
ENV GOPATH /go
ENV API_ROOT /go/src/github.com/yongwoon/echo-blog

RUN apk update && apk add --no-cache bash git vim openssh curl make

RUN GO111MODULE=off go get github.com/oxequa/realize

WORKDIR $API_ROOT
COPY go.mod go.sum ./
RUN go mod download
COPY . .
